AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0
  Exclude:
    - 'test/fixtures/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Security/Eval:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundKeyword:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
